# -*- coding: utf-8 -*-
"""Logistic_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2et5zRxWOCPeQBlfeLXcQqqW5uJJTAl
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
st = pd.read_csv('/content/TATAMOTORS 2.csv')
st.head()
st.info()
st.describe()

A = st[['Profit_achieveable']]
B = st['class_profit']
plt.scatter(A,B)
plt.xlabel('Profit_achieveable')
plt.ylabel('class_profit')

X = st[['Profit_achieveable',	'Loss_achieveable']]
Y = st['class_profit']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.20,random_state = 0)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)
model = LogisticRegression()
model.fit(X_train,Y_train)
print("Intercept:",model.intercept_)
print("Coefficient:",model.coef_)
print(model.score(X_train,Y_train))
print(model.score(X_test,Y_test))